# **Array Operations**

## **Linear Search**

In [78]:
import numpy as np
li=[20,15,12,114,19,16,13]
myarray=np.array(li)

In [81]:
myarray=np.array(li)

In [82]:
user_input=input("Enter the value to check in the array: ")
n1=int(user_input)

In [83]:
found=False
for i in myarray:
    if i==n1:
        print(f'The entered value {n1} is inside your array')
        found=True
        break
    else:
        pass
if not found:
    print("Value does not existed")

Value does not existed


## **Sorting the matrix**

In [123]:
def mysorting(arr):
    n=len(arr)
    for i in range(n):
        for j in range(0,n-i-1):
            if arr[j]>arr[j+1]:
                arr[j],arr[j+1]=arr[j+1],arr[j] 
    return arr

In [126]:
array4=[10,2,11,32,14,12]
mysorting(array4)

[2, 10, 11, 12, 14, 32]

## **Different Operations on the array**

### searching in the array

### Addition

In [85]:
array2=np.array([10,20,30,40,50,60,70])
array3=np.array([1,2,3,4,5,6,7])

In [86]:
result_addition=np.add(array2,array3)
result_addition


array([11, 22, 33, 44, 55, 66, 77])

### Multiplication

In [87]:
result_multiply=np.multiply(array2,array3)
result_multiply


array([ 10,  40,  90, 160, 250, 360, 490])

### Merge the two array


In [89]:
result_concatinated=np.concatenate((array2,array3))
result_concatinated

array([10, 20, 30, 40, 50, 60, 70,  1,  2,  3,  4,  5,  6,  7])

### Converting the array into the matrix

In [93]:
result_matrix=np.row_stack((array2,array3))
result_matrix

array([[10, 20, 30, 40, 50, 60, 70],
       [ 1,  2,  3,  4,  5,  6,  7]])

### Checking the size of the matrix


In [97]:
sizeofmat=result_matrix.shape
sizeofmat

(2, 7)

### multiplying the 2D array(matrix)

In [102]:
matrix1=result_matrix
matrix2=np.array([[1,1,1,1,1,1,1],[1,1,1,1,1,1,1]])


In [105]:
multiply_of_matrix=matrix1*matrix2
multiply_of_matrix

array([[10, 20, 30, 40, 50, 60, 70],
       [ 1,  2,  3,  4,  5,  6,  7]])